#skip_checks:
#  - CKV_AWS_144   # S3 cross-region replication
#  - CKV_AWS_18    # S3 access logging
#  - CKV2_AWS_61   # S3 lifecycle
#  - CKV2_AWS_62   # S3 notifications
#  - CKV2_AWS_12   # default SG restrictive
#  - CKV_AWS_130   # public subnet (intentional)
#  - CKV_AWS_338   # "Ensure CloudWatch log groups retains logs for at least 1 year" (not part of my scope boss)
#  - CKV_AWS_158   # "Ensure that CloudWatch Log Group is encrypted by KMS" (but i need to keep things cheap)
#  - CKV_AWS_145:  # "Ensure that S3 buckets are encrypted with KMS by default" (same as above)
#  - CKV2_AWS_11:  # "Ensure VPC flow logging is enabled in all VPCs" (not in this sandbox)


# .checkov.yaml
# 1) the checks you already skip
skip-check: CKV_AWS_144,CKV_AWS_18,CKV2_AWS_61,CKV2_AWS_62,CKV2_AWS_12,CKV_AWS_130,CKV_AWS_338,CKV_AWS_145,CKV_AWS_158,CKV2_AWS_11
