[project]
name = "fraud-detection-system"
version = "0.0.0"
description = "Portfolio fraud detection project"
requires-python = ">=3.12"
authors = [{name="Esosa Orumwese", email="eorumwese@gmail.com"}]

[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"
