"""Constant values used across the S9 validation pipeline."""

from __future__ import annotations

from pathlib import Path

VALIDATION_DATASET_ID = "validation_bundle_1A"
DATASET_OUTLET_CATALOGUE = "outlet_catalogue"
DATASET_S3_CANDIDATE_SET = "s3_candidate_set"
DATASET_S3_INTEGERISED_COUNTS = "s3_integerised_counts"
DATASET_S3_SITE_SEQUENCE = "s3_site_sequence"
DATASET_S6_MEMBERSHIP = "s6_membership"

EVENT_FAMILY_NB_FINAL = "rng_event.nb_final"
EVENT_FAMILY_SEQUENCE_FINALIZE = "rng_event.sequence_finalize"
EVENT_FAMILY_SITE_SEQUENCE_OVERFLOW = "rng_event.site_sequence_overflow"
EVENT_FAMILY_HURDLE_BERNOULLI = "rng_event_hurdle_bernoulli"
EVENT_FAMILY_GAMMA_COMPONENT = "rng_event_gamma_component"
EVENT_FAMILY_POISSON_COMPONENT = "rng_event_poisson_component"
EVENT_FAMILY_ZTP_REJECTION = "rng_event_ztp_rejection"
EVENT_FAMILY_ZTP_RETRY_EXHAUSTED = "rng_event_ztp_retry_exhausted"
EVENT_FAMILY_ZTP_FINAL = "rng_event_ztp_final"
EVENT_FAMILY_GUMBEL_KEY = "rng_event_gumbel_key"
EVENT_FAMILY_RESIDUAL_RANK = "rng_event_residual_rank"
EVENT_FAMILY_DIRICHLET_GAMMA_VECTOR = "rng_event_dirichlet_gamma_vector"
EVENT_FAMILY_ANCHOR = "rng_event_anchor"

TRACE_LOG_ID = "rng_trace_log"
AUDIT_LOG_ID = "rng_audit_log"

S6_RECEIPT_DATASET_ID = "s6_validation_receipt"

BUNDLE_INDEX_KIND_SUMMARY = "summary"
BUNDLE_INDEX_KIND_TABLE = "table"
BUNDLE_INDEX_KIND_TEXT = "text"

BUNDLE_INDEX_SUMMARY_FILES = {
    "MANIFEST.json",
    "s9_summary.json",
}

NON_CONSUMING_FAMILIES = {
    EVENT_FAMILY_ANCHOR,
    EVENT_FAMILY_NB_FINAL,
    EVENT_FAMILY_ZTP_REJECTION,
    EVENT_FAMILY_ZTP_RETRY_EXHAUSTED,
    EVENT_FAMILY_ZTP_FINAL,
    EVENT_FAMILY_RESIDUAL_RANK,
    EVENT_FAMILY_SEQUENCE_FINALIZE,
    EVENT_FAMILY_SITE_SEQUENCE_OVERFLOW,
}

RNG_EVENT_DATASETS = (
    EVENT_FAMILY_ANCHOR,
    EVENT_FAMILY_HURDLE_BERNOULLI,
    EVENT_FAMILY_GAMMA_COMPONENT,
    EVENT_FAMILY_POISSON_COMPONENT,
    EVENT_FAMILY_NB_FINAL,
    EVENT_FAMILY_ZTP_REJECTION,
    EVENT_FAMILY_ZTP_RETRY_EXHAUSTED,
    EVENT_FAMILY_ZTP_FINAL,
    EVENT_FAMILY_GUMBEL_KEY,
    EVENT_FAMILY_RESIDUAL_RANK,
    EVENT_FAMILY_DIRICHLET_GAMMA_VECTOR,
    EVENT_FAMILY_SEQUENCE_FINALIZE,
    EVENT_FAMILY_SITE_SEQUENCE_OVERFLOW,
)

BUNDLE_FILES = {
    "MANIFEST.json",
    "parameter_hash_resolved.json",
    "manifest_fingerprint_resolved.json",
    "rng_accounting.json",
    "s9_summary.json",
    "egress_checksums.json",
    "index.json",
}

STAGE_LOG_ROOT = Path("logs/stages/s9_validation")
STAGE_LOG_FILENAME = "S9_STAGES.jsonl"

__all__ = [
    "VALIDATION_DATASET_ID",
    "DATASET_OUTLET_CATALOGUE",
    "DATASET_S3_CANDIDATE_SET",
    "DATASET_S3_INTEGERISED_COUNTS",
    "DATASET_S3_SITE_SEQUENCE",
    "DATASET_S6_MEMBERSHIP",
    "EVENT_FAMILY_NB_FINAL",
    "EVENT_FAMILY_SEQUENCE_FINALIZE",
    "EVENT_FAMILY_SITE_SEQUENCE_OVERFLOW",
    "EVENT_FAMILY_HURDLE_BERNOULLI",
    "EVENT_FAMILY_GAMMA_COMPONENT",
    "EVENT_FAMILY_POISSON_COMPONENT",
    "EVENT_FAMILY_ZTP_REJECTION",
    "EVENT_FAMILY_ZTP_RETRY_EXHAUSTED",
    "EVENT_FAMILY_ZTP_FINAL",
    "EVENT_FAMILY_GUMBEL_KEY",
    "EVENT_FAMILY_RESIDUAL_RANK",
    "EVENT_FAMILY_DIRICHLET_GAMMA_VECTOR",
    "EVENT_FAMILY_ANCHOR",
    "TRACE_LOG_ID",
    "AUDIT_LOG_ID",
    "S6_RECEIPT_DATASET_ID",
    "BUNDLE_INDEX_KIND_SUMMARY",
    "BUNDLE_INDEX_KIND_TABLE",
    "BUNDLE_INDEX_KIND_TEXT",
    "BUNDLE_INDEX_SUMMARY_FILES",
    "NON_CONSUMING_FAMILIES",
    "RNG_EVENT_DATASETS",
    "BUNDLE_FILES",
    "STAGE_LOG_ROOT",
    "STAGE_LOG_FILENAME",
]
