"""Segment 1B package exports."""

from .s0_gate.l2.runner import S0GateRunner, GateInputs, GateResult
from .s1_tile_index import (
    InclusionRule,
    RunnerConfig as S1RunnerConfig,
    S1RunResult,
    S1TileIndexRunner,
    S1TileIndexValidator,
    ValidatorConfig as S1ValidatorConfig,
)
from .s2_tile_weights import (
    MassComputation,
    PatCounters,
    PreparedInputs as S2PreparedInputs,
    RunnerConfig as S2RunnerConfig,
    S2Error,
    S2RunResult,
    S2TileWeightsRunner,
    S2TileWeightsValidator,
    ValidatorConfig as S2ValidatorConfig,
)
from .s3_requirements import (
    AggregationResult as S3AggregationResult,
    PreparedInputs as S3PreparedInputs,
    RunnerConfig as S3RunnerConfig,
    S3Error,
    S3RequirementsRunner,
    S3RequirementsValidator,
    S3RunResult,
    S3ValidatorConfig,
    build_run_report as s3_build_run_report,
    compute_requirements as s3_compute_requirements,
    materialise_requirements as s3_materialise_requirements,
    prepare_inputs as s3_prepare_inputs,
)
from .s4_alloc_plan import (
    AggregationContext as S4AggregationContext,
    AllocationResult as S4AllocationResult,
    PreparedInputs as S4PreparedInputs,
    RunnerConfig as S4RunnerConfig,
    S4AllocPlanRunner,
    S4AllocPlanValidator,
    S4Error,
    S4RunResult,
    ValidatorConfig as S4ValidatorConfig,
    allocate_sites as s4_allocate_sites,
    build_allocation as s4_build_allocation,
    build_run_report as s4_build_run_report,
    err as s4_err,
    materialise_allocation as s4_materialise_allocation,
    prepare_inputs as s4_prepare_inputs,
)
from .s5_site_tile_assignment import (
    RunnerConfig as S5RunnerConfig,
    S5Error,
    S5RunResult,
    S5SiteTileAssignmentRunner,
    S5SiteTileAssignmentValidator,
    ValidatorConfig as S5ValidatorConfig,
    err as s5_err,
)

__all__ = [
    "S0GateRunner",
    "GateInputs",
    "GateResult",
    "InclusionRule",
    "S1RunnerConfig",
    "S1RunResult",
    "S1TileIndexRunner",
    "S1TileIndexValidator",
    "S1ValidatorConfig",
    "MassComputation",
    "PatCounters",
    "S2PreparedInputs",
    "S2RunnerConfig",
    "S2RunResult",
    "S2TileWeightsRunner",
    "S2TileWeightsValidator",
    "S2ValidatorConfig",
    "S2Error",
    "S3AggregationResult",
    "S3PreparedInputs",
    "S3RunnerConfig",
    "S3RunResult",
    "S3RequirementsRunner",
    "S3RequirementsValidator",
    "S3ValidatorConfig",
    "S3Error",
    "s3_build_run_report",
    "s3_compute_requirements",
    "s3_materialise_requirements",
    "s3_prepare_inputs",
    "S4AggregationContext",
    "S4AllocationResult",
    "S4PreparedInputs",
    "S4RunnerConfig",
    "S4RunResult",
    "S4AllocPlanRunner",
    "S4AllocPlanValidator",
    "S4ValidatorConfig",
    "S4Error",
    "s4_allocate_sites",
    "s4_build_allocation",
    "s4_build_run_report",
    "s4_err",
    "s4_materialise_allocation",
    "s4_prepare_inputs",
    "S5RunnerConfig",
    "S5RunResult",
    "S5SiteTileAssignmentRunner",
    "S5SiteTileAssignmentValidator",
    "S5ValidatorConfig",
    "S5Error",
    "s5_err",
]
