name: Daily Cost Report

on:
  schedule:
    # 06:30 UTC = 08:30 CEST (enough buffer for CE data to refresh)
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  ce-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: eu-west-2
          # either via secrets:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # or via an assumed role:
          # role-to-assume:      ${{ secrets.AWS_ROLE_ARN }}

      - name: Determine dates
        id: dates
        run: |
          # GitHub Actions Ubuntu runners have GNU date
          YESTERDAY=$(date -u -d "yesterday" '+%Y-%m-%d')
          echo "yesterday=$YESTERDAY" >> $GITHUB_OUTPUT

      - name: Query Cost Explorer for yesterday
        id: cost
        run: |
          AMOUNT=$(aws ce get-cost-and-usage \
            --time-period Start=${{ steps.dates.outputs.yesterday }},End=${{ steps.dates.outputs.yesterday }} \
            --granularity DAILY \
            --metrics UnblendedCost \
            --query "ResultsByTime[0].Total.UnblendedCost.Amount" \
            --output text)
          echo "amount=$AMOUNT" >> $GITHUB_OUTPUT

      - name: Post comment to Issue #1
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 1
          body: |
            ### 💰 AWS Spend for ${{ steps.dates.outputs.yesterday }}
            Yesterday’s total: **£${{ steps.cost.outputs.amount }}**
