name: Manual Sandbox Teardown

on:
  workflow_dispatch:                # exposes a “Run workflow” button in the Actions tab
    inputs:
      confirm:
        description: Type "NUKEME" to confirm
        required: true

jobs:
  teardown:
    runs-on: ubuntu-latest
    permissions:
      id-token: write                # if you’re using OIDC to assume an AWS role
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        aws-region: eu-west-2

    - name: Set up Python & install deps
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: |
        python -m pip install poetry
        poetry install --no-interaction --no-ansi --with dev

    - name: Run sandbox teardown
      run: |
        # this will skip prompts and safety-check (we already confirmed in the UI)
        infra/scripts/nuke.sh --force
